[package]
name = "user_struct"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
description = "Zainium OS Zainium OS smart filesystem structure creator"
authors = ["Zainium Dynamics"]
license = "GPL-3.0"
publish = false

[lib]
name = "user_struct"
path = "src/lib.rs"

[[bin]]
name = "struct"
path = "src/main.rs"

[lints]
workspace = true
